# Generated by Django 2.2.3 on 2019-08-04 20:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=100)),
                ('description', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
    ]
