# Generated by Django 2.2.3 on 2019-08-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='bodytext',
            new_name='body_text',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=200),
        ),
    ]
